version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: whoreads-local-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: # 한글 깨짐 방지
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      # 1. 데이터 저장소 (로컬에 저장해서 껐다 켜도 데이터 유지)
      - ./db/data:/var/lib/mysql
      # 2. [핵심] 초기화 스크립트 자동 실행 폴더 연결
      - ./db/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always